### ISSUE TITLE
Is it possible to have mgem not in the root of a repository?

### ISSUE THREAD

**Issue by kotovalexarian** [mruby/mgem-list#338]
I develop [a C library](https://github.com/tailix/libkernaux) and have all bindings in the directory `pkgs/` (`pkgs/ruby/`, `pkgs/rust/`, `pkgs/python/`, etc). I want to create MRuby gem in the same manner in `pkgs/mruby/`. It it posiible to put such MRuby gem to this list? I don't see any key for YAML to specify the MRuby gem path inside my repository, only `repository` exists.

I know that it's possible to specify dependency as follows:
```ruby
conf.gem github: 'tailix/libkernaux', path: 'pkgs/mruby'
```
But I want this to work:
```ruby
conf.gem mgem: 'kernaux'
```
If this is impossible, will the following work?
```ruby
conf.gem mgem: 'kernaux', path: 'pkgs/mruby'
```

**Comment by dearblue** [comment]
Currently mruby does not have the ability to manage many git repositories in a single directory.

A somewhat similar feature is the `MRuby::Build#gem_clone_dir=` accessor, but it is not recommended.
The reason is that it cannot distinguish between different repositories if the end of directory names are the same.

For example, the following cases both try to clone to the same directory.

```ruby
# build_config.rb

MRuby::Build.new("test") do |conf|
  ...
  conf.gem_clone_dir = File.expand("~/dir/to/pkgs/mruby")
  conf.gem git: "https://a-host.example/userA/mruby-gem.git"        ## this repository is used
end

MRuby::Build.new("anothor-test") do |conf|
  ...
  conf.gem_clone_dir = File.expand("~/dir/to/pkgs/mruby")
  conf.gem git: "https://anothor-host.example/userB/mruby-gem.git"  ## this repository is ignored
end
```

Also, multiple configurations cannot specify different commit hashes for the same git repository at the same time.

&lt;!-- I secretly using the `MRuby::Build#gem_clone_dir=` accessor in my test builds. --&gt;

Last but not least, if you want to continue this topic, it would be better to do so in the https://github.com/mruby/mruby repository.

**Comment by kotovalexarian** [comment]
Ok, thank you for the answer
